//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONS.PortalMQDI.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONS.PortalMQDI.Data.Resources.DatabaseQueries", typeof(DatabaseQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT a.nom_curto, r.anomes_referencia,a.nom_longo,a.age_mrid, COALESCE(r.age_mrid, r.mrid) as mrid
        ///    FROM tb_contestacao c
        ///    INNER JOIN tb_resultadoindicador r ON c.id_resultadoindicador = r.id_resultadoindicador
        ///    INNER JOIN tb_agente a ON (r.age_mrid = a.age_mrid AND r.age_mrid IS NOT NULL) OR (r.mrid = a.age_mrid AND r.age_mrid IS NULL)
        ///    {filtroAnoMes}
        ///    ORDER BY COALESCE(r.age_mrid, r.mrid) DESC.
        /// </summary>
        internal static string QUERY_BUSCAR_AGENTE {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_AGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select distinct a.* from tb_agente a
        ///    inner join tb_grandeza g on a.age_mrid=g.age_mrid and a.anomes_referencia=g.anomes_referencia
        ///    Where g.cod_lscinf=&apos;&apos; and g.anomes_referencia=&apos;{anoMes}&apos; {filtroAgentes}.
        /// </summary>
        internal static string QUERY_BUSCAR_AGENTE_CONSULTAR_MEDIDA {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_AGENTE_CONSULTAR_MEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select distinct a.* from tb_agente a
        ///    inner join tb_resultadoindicador ri on ri.mrid=a.age_mrid and ri.anomes_referencia=a.anomes_referencia
        ///    where a.anomes_referencia=&apos;{anoMes}&apos; {filtroAgentes}.
        /// </summary>
        internal static string QUERY_BUSCAR_AGENTE_INDICADOR {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_AGENTE_INDICADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select tr.nom_tprecurso, i.nom_curto, i.nom_longo, i.ido_ons, ri.*, ti.nom_tpindicador, ti.cod_tpindicador, i.ins_mrid, c.dsc_contestacao, rc.cmn_resultado   
        ///    from tb_instalacao i 
        ///    inner join tb_resultadoindicador ri on i.ins_mrid=ri.mrid and i.anomes_referencia=ri.anomes_referencia
        ///    inner join tb_tprecurso tr on tr.id_tprecurso=ri.id_tprecurso
        ///    inner join tb_tpindicador ti on ti.id_tpindicador = ri.id_tpindicador
        ///    inner join tb_agente a on ri.age_mrid=a.age_mrid and ri.anomes_referenc [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_CONSULTA_INDICADOR_INSTALACAO_POR_FILTRO {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_CONSULTA_INDICADOR_INSTALACAO_POR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select a.ido_ons IdAgente, a.nom_longo NomeAgente, g.cos_id CentroOperacao, i.nom_longo NomeInstalacao, i.ido_ons IdInstalacao, g.ido_ons Id_ponto, g.nom_enderecofisico Endereco,
        ///    g.cod_lscinf UTRCD, ri.val_mensal Disponibilidade, g.anomes_referencia, rie.flg_expurgoestadooperativo ExpurgoEstadoOperativo, rie.flg_expurgoproblemapi ExpurgoHistoricoPI,
        ///	ri.val_anual IndiceAnual, ri.flg_violacaoanual FlagViolacaoAnual
        ///    from tb_grandeza g 
        ///    inner join tb_instalacao i on g.ins_mrid=i.ins_mrid and g. [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_INSTALACAO_RANGE_DATA {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_INSTALACAO_RANGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///tr.nom_tprecurso, i.nom_curto, i.nom_longo, i.ido_ons, ri.*, 
        ///ti.nom_tpindicador, ti.cod_tpindicador, i.ins_mrid, c.dsc_contestacao, rc.cmn_resultado, c.id_contestacao, rc.id_tpresultadocontestacao,
        ///(
        ///    SELECT COUNT(*)
        ///    FROM tb_resultadoindicador r
        ///    INNER JOIN tb_grandeza g ON g.grd_mrid=r.mrid AND g.anomes_referencia=r.anomes_referencia
        ///    LEFT JOIN tb_equipamento e ON g.ter_mrid = e.ter_mrid AND g.anomes_referencia=e.anomes_referencia
        ///    LEFT JOIN tb_contestacao c ON c.id_resulta [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_INSTALACAO_RECURSO {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_INSTALACAO_RECURSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select tr.nom_tprecurso, i.nom_curto, i.nom_longo, i.ido_ons, ri.*, ti.nom_tpindicador, ti.cod_tpindicador  
        ///    from tb_instalacao i 
        ///    inner join tb_resultadoindicador ri on i.ins_mrid=ri.mrid and i.anomes_referencia=ri.anomes_referencia
        ///    inner join tb_tprecurso tr on tr.id_tprecurso=ri.id_tprecurso
        ///    inner join tb_tpindicador ti on ti.id_tpindicador = ri.id_tpindicador
        ///    inner join tb_agente a on ri.age_mrid=a.age_mrid and ri.anomes_referencia=a.anomes_referencia
        ///    where ri.anomes_refere [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_INSTALACAO_VIEW_POR_FILTRO {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_INSTALACAO_VIEW_POR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select tr.nom_tprecurso, a.nom_curto, a.nom_longo, a.ido_ons, ri.*, ti.nom_tpindicador, ti.cod_tpindicador  
        ///    from tb_agente a 
        ///    inner join tb_resultadoindicador ri on a.age_mrid=ri.mrid and a.anomes_referencia=ri.anomes_referencia
        ///    inner join tb_tprecurso tr on tr.id_tprecurso=ri.id_tprecurso
        ///    inner join tb_tpindicador ti on ti.id_tpindicador = ri.id_tpindicador 
        ///    where ri.anomes_referencia in(&apos;{datas}&apos;)
        ///    and a.age_mrid like &apos;{ageMrid}&apos;
        ///    {filtroTipoIndicador}
        ///    {filtroFragVio [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_VIEW_POR_FILTRO {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_VIEW_POR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select tr.nom_tprecurso, a.nom_curto, a.nom_longo, a.ido_ons, ri.*, ti.nom_tpindicador, ti.cod_tpindicador, c.dsc_contestacao, rc.cmn_resultado, c.id_contestacao, rc.id_tpresultadocontestacao
        ///    from tb_agente a 
        ///    inner join tb_resultadoindicador ri on a.age_mrid=ri.mrid and a.anomes_referencia=ri.anomes_referencia
        ///    inner join tb_tprecurso tr on tr.id_tprecurso=ri.id_tprecurso
        ///    inner join tb_tpindicador ti on ti.id_tpindicador = ri.id_tpindicador
        ///    left join tb_contestacao c on c.id_resulta [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_VIEW_POR_FILTRO_CONSULTAINDICADORAGENTE {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_VIEW_POR_FILTRO_CONSULTAINDICADORAGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT 
        ///        g.cod_lscinf, 
        ///        g.age_mrid AS age_grandeza, 
        ///        u.age_mrid AS agedono, 
        ///        u.ido_ons, 
        ///        u.ido_ons as UTR_CD,
        ///        IIF(g.age_mrid=u.age_mrid, &apos;*&apos;, &apos;&apos;) AS dono, 
        ///        ur.*,  
        ///        ti.cod_tpindicador
        ///    FROM  
        ///        tb_grandeza g
        ///    INNER JOIN  
        ///        tb_utrcd u 
        ///    ON 
        ///        g.cod_lscinf = u.cod_lscinf AND g.anomes_referencia = u.anomes_referencia
        ///    INNER JOIN  
        ///        tb_resultadoindicador ur
        ///    ON 
        ///        u.utrcd_mrid  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_VIEW_POR_FILTRO_RESULTADOINDICADOR {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_VIEW_POR_FILTRO_RESULTADOINDICADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT 
        ///        u.ido_ons AS UTR_CD, 
        ///        u.cod_lscinf, 
        ///        ur.*,  
        ///        ti.cod_tpindicador, 
        ///        c.dsc_contestacao, 
        ///        rc.cmn_resultado, 
        ///        c.id_contestacao, 
        ///        rc.id_tpresultadocontestacao,
        ///        IIF(gr.age_mrid=u.age_mrid, &apos;*&apos;, &apos;&apos;) as dono
        ///    FROM  
        ///        tb_resultadoindicador ur
        ///    INNER JOIN  
        ///        tb_utrcd u 
        ///    ON 
        ///        u.utrcd_mrid = ur.mrid AND u.anomes_referencia = ur.anomes_referencia
        ///    INNER JOIN  
        ///        tb_tpindicador  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_BUSCAR_VIEW_SSCl_POR_FILTRO {
            get {
                return ResourceManager.GetString("QUERY_BUSCAR_VIEW_SSCl_POR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select tr.nom_tprecurso, a.nom_curto, a.nom_longo, a.ido_ons, ri.*, ti.nom_tpindicador, ti.cod_tpindicador, c.dsc_contestacao, rc.cmn_resultado, c.id_contestacao,
        ///rc.id_tpresultadocontestacao
        ///from tb_agente a 
        ///inner join tb_resultadoindicador ri on a.age_mrid=ri.mrid and a.anomes_referencia=ri.anomes_referencia
        ///inner join tb_tprecurso tr on tr.id_tprecurso=ri.id_tprecurso
        ///inner join tb_tpindicador ti on ti.id_tpindicador = ri.id_tpindicador
        ///left join tb_contestacao c on c.id_resultadoindicador=ri.id_r [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_CONSULTA_INDICADOR_AGENTE_VIEW_POR_FILTRO {
            get {
                return ResourceManager.GetString("QUERY_CONSULTA_INDICADOR_AGENTE_VIEW_POR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT u.ido_ons AS UTR_CD, 
        ///               u.cod_lscinf, 
        ///               ur.*,  
        ///               ti.cod_tpindicador, 
        ///               c.dsc_contestacao, 
        ///               rc.cmn_resultado, 
        ///               c.id_contestacao, 
        ///               rc.id_tpresultadocontestacao
        ///FROM tb_resultadoindicador ur
        ///INNER JOIN tb_utrcd u ON u.utrcd_mrid=ur.mrid AND u.anomes_referencia=ur.anomes_referencia
        ///INNER JOIN tb_tpindicador ti ON ti.id_tpindicador = ur.id_tpindicador
        ///LEFT JOIN tb_contestacao c ON c.id_r [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_CONSULTA_INDICADOR_SSCL {
            get {
                return ResourceManager.GetString("QUERY_CONSULTA_INDICADOR_SSCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select g.ido_ons, g.cod_lscinf, g.dsc_grandeza, g.nom_enderecofisico, r.*, e.tprede, c.dsc_contestacao, rc.cmn_resultado, rc.id_tpresultadocontestacao, c.id_contestacao, s.*
        ///    from tb_resultadoindicador r
        ///    inner join tb_grandeza g on g.grd_mrid=r.mrid and g.anomes_referencia=r.anomes_referencia
        ///    left join tb_equipamento e on g.ter_mrid =e.ter_mrid and g.anomes_referencia=e.anomes_referencia
        ///    left join tb_contestacao c on c.id_resultadoindicador=r.id_resultadoindicador
        ///    left join tb_result [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_CONSULTAR_RECURSOS {
            get {
                return ResourceManager.GetString("QUERY_CONSULTAR_RECURSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WITH SubQuery_Recurso AS (
        ///    SELECT g.*, 
        ///        c.dsc_contestacao as recursoAnalistaContestacao,
        ///        rc.cmn_resultado as recursoOnsContestacao,
        ///        c.id_contestacao as recursoOnsIdContestacao,
        ///        rc.id_tpresultadocontestacao as recursoOnsStatus,
        ///        r.id_tprecurso,
        ///        r.flg_violacaoanual as recursoFragAnual,
        ///        r.flg_violacaomensal as recursoFragMensal,
        ///        r.val_anual as recursoValorMensal,
        ///        r.val_mensal as recursoValorAnual,
        ///        r.id_resultadoindica [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_CONTESTACAO_INSTALACAO_RECURSO {
            get {
                return ResourceManager.GetString("QUERY_CONTESTACAO_INSTALACAO_RECURSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WITH CTE_Instalacao AS (
        ///    SELECT 
        ///        tr.nom_tprecurso, 
        ///        i.nom_curto, 
        ///        i.nom_longo, 
        ///        i.ido_ons, 
        ///        ri.id_resultadoindicador AS ri_id_resultadoindicador,
        ///        ri.cos_id AS ri_cos_id,
        ///        ri.mrid AS ri_mrid,
        ///        ti.nom_tpindicador AS ti_nom_tpindicador, 
        ///        ti.cod_tpindicador AS ti_cod_tpindicador,
        ///        i.ins_mrid, 
        ///        ri.anomes_referencia,
        ///        a.age_mrid,
        ///        ri.id_tpindicador,
        ///        ri.cos_id,
        ///        ri.val_anual as inst [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_EXPORTAR_INSTALACAO {
            get {
                return ResourceManager.GetString("QUERY_EXPORTAR_INSTALACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select distinct g.age_mrid age_grandeza, u.age_mrid agedono, 
        ///    IIF(g.age_mrid=u.age_mrid,u.ido_ons+&apos;*&apos;,u.ido_ons+&apos;&apos;) ido_ons, 
        ///    IIF(g.age_mrid=u.age_mrid,g.cod_lscinf+&apos;*&apos;,g.cod_lscinf+&apos;&apos;) cod_lscinf 
        ///    from tb_grandeza g
        ///    inner join tb_utrcd u on g.cod_lscinf=u.cod_lscinf and g.anomes_referencia=u.anomes_referencia
        ///    where g.anomes_referencia=&apos;{anoMesFormatado}&apos; and g.age_mrid=&apos;{codAgente}&apos; and g.cod_lscinf != &apos;&apos;.
        /// </summary>
        internal static string QUERY_FILTRAR_AGENTES_SCADA {
            get {
                return ResourceManager.GetString("QUERY_FILTRAR_AGENTES_SCADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT anomes_referencia FROM tb_resultadoindicador where anomes_referencia=&apos;{anoMes}&apos; and cos_id like &apos;%{centro}%&apos;.
        /// </summary>
        internal static string QUERY_GERAR_CALENDARIO {
            get {
                return ResourceManager.GetString("QUERY_GERAR_CALENDARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select i.ido_ons IdInstalacao, i.nom_curto Instalacao, g.cos_id, g.ido_ons IdPonto, g.dsc_grandeza, g.tprede, g.age_mrid from tb_grandeza g
        ///    inner join tb_instalacao i on i.ins_mrid=g.ins_mrid and i.anomes_referencia=g.anomes_referencia
        ///    Where g.anomes_referencia=&apos;{anoMes}&apos; and g.cod_lscinf=&apos;&apos; and g.age_mrid In (&apos;{ageMrid}&apos;)
        ///    order by Instalacao, g.cos_id, g.dsc_grandeza.
        /// </summary>
        internal static string QUERY_INSTALACAO_CONSULTAR_MEDIDA {
            get {
                return ResourceManager.GetString("QUERY_INSTALACAO_CONSULTAR_MEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select i.ido_ons IdInstalacao, i.nom_curto Instalacao, g.cos_id, g.ido_ons IdPonto, g.dsc_grandeza, g.tprede, g.age_mrid from tb_grandeza g
        ///    inner join tb_instalacao i on i.ins_mrid=g.ins_mrid and i.anomes_referencia=g.anomes_referencia
        ///    Where g.anomes_referencia=&apos;{anoMes}&apos; and g.cod_lscinf=&apos;&apos; and g.age_mrid In ({ageMridList})
        ///    order by Instalacao, g.cos_id, g.dsc_grandeza.
        /// </summary>
        internal static string QUERY_INSTALACAO_CONSULTAR_MEDIDA_LIST {
            get {
                return ResourceManager.GetString("QUERY_INSTALACAO_CONSULTAR_MEDIDA_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT u.ido_ons AS UTR_CD, u.cod_lscinf, ur.*, ti.cod_tpindicador,IIF(gr.age_mrid=u.age_mrid, &apos;*&apos;, &apos;&apos;) as dono
        ///FROM  tb_resultadodiario ur
        ///INNER JOIN  tb_utrcd u ON u.utrcd_mrid = ur.mrid AND u.anomes_referencia = ur.anomes_referencia
        ///INNER JOIN  tb_tpindicador ti ON ti.id_tpindicador = ur.id_tpindicador
        ///INNER JOIN(SELECT DISTINCT g.cod_lscinf, g.anomes_referencia, g.age_mrid FROM tb_grandeza g
        ///WHERE g.age_mrid = &apos;{agente}&apos; AND g.cod_lscinf != &apos;&apos;) AS gr  
        ///ON gr.cod_lscinf = u.cod_lscinf AND  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_RESULTADO_DIARIO_DCD {
            get {
                return ResourceManager.GetString("QUERY_RESULTADO_DIARIO_DCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT rd.id_resultadodiario, i.nom_curto,         g.ido_ons,         g.dsc_grandeza,         g.tprede,         cod_lscinf,         g.nom_enderecofisico,         rd.val_dispdiario,         rd.flg_dispdiario FROM tb_resultadodiario rd INNER JOIN tb_grandeza g ON g.grd_mrid = rd.mrid AND g.anomes_referencia = rd.anomes_referencia INNER JOIN tb_instalacao i ON i.ins_mrid = g.ins_mrid AND i.anomes_referencia = g.anomes_referencia WHERE rd.dat_resultado = &apos;{data}&apos; AND g.age_mrid = &apos;{agente}&apos; AND rd.id_tprecurso  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string QUERY_RESULTADO_DIARIO_DRSC {
            get {
                return ResourceManager.GetString("QUERY_RESULTADO_DIARIO_DRSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT g.nom_enderecofisico, g.ido_ons
        ///    FROM tb_grandeza g
        ///    INNER JOIN tb_resultadoindicador ri on g.age_mrid = ri.age_mrid
        ///    WHERE g.age_mrid = &apos;{codAgente}&apos; AND g.anomes_referencia = &apos;{dataFormatada}&apos; AND ri.id_tpindicador = 2 AND g.ido_ons is not null.
        /// </summary>
        internal static string QUERY_SUPERVISAO_TEMPO_REAL {
            get {
                return ResourceManager.GetString("QUERY_SUPERVISAO_TEMPO_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT a.* FROM tb_agente a
        ///    INNER JOIN tb_grandeza g 
        ///    ON a.age_mrid = g.age_mrid AND a.anomes_referencia = g.anomes_referencia
        ///    {filtroAnoMesReferencia}
        ///    {filtroAgentes}
        ///    ORDER BY a.nom_curto.
        /// </summary>
        internal static string QUERY_TODOS_AGENTE_POR_GRANDEZA {
            get {
                return ResourceManager.GetString("QUERY_TODOS_AGENTE_POR_GRANDEZA", resourceCulture);
            }
        }
    }
}
